### ISSUE TITLE
Parameter passing

### ISSUE THREAD

**Issue by henryiii** [Princeton-Penn-Vents/princeton-penn-flowmeter#4]
@davidlange6,

would it make sense to setup a structure to hold the data, something like this:

```python
from dataclasses import dataclass

@dataclass
class SimParams:
    current_time: float  # Current sim time, in seconds, starts from 0 , (seconds)
    max_time: float  # Maximum window time (s)
    sampling_rate : float  # in Hz
    max_flow: float  # L/minute
    tidal_volume: float # L
    recovery_tau: float
    peep: float  # cm H20
    inhale_exhale_ratio: float = 0.5 # (optional) (unused)
```

Then you could just do:

```python
params = SimParams(
    current_time=0,
    max_time=120.0,
    sample_rate=100.0,
    breathing_rate=12.0,
    max_flow=12.0,  # L/m
    tidal_volume=0.6,  # L
    peep=4,  # cm H20
)
```

And pass it around - that way all functions have access to all sim parameters as `params.peep` and such. You still might want a few parameters specific to some functions, but this could hold the overall "initial parameters". We could eventually write a method that turns it into json to store it in the output packet.

Just a thought.

**Comment by davidlange6** [comment]
I turned the sim into a class - so this comes for free now
