### ISSUE TITLE
conflict with scipy.interpolate

### ISSUE THREAD

**Issue by davidlange6** [Princeton-Penn-Vents/princeton-penn-flowmeter#47]
I'm working on a module in the processor package. It seems that logging.py prevents me from using scipy.interpolate.

  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 6, in <module>
    import logging
  File "/Users/lange/covid/gui/princeton-penn-flowmeter/processor/logging.py", line 7, in <module>
    from processor.config import config, get_data_dir

**Comment by davidlange6** [comment]
can reproduce by 
cd processor
python3 -c "import scipy.interpolate"

**Comment by henryiii** [comment]
We really need to make this a package, would solve this issues... ~~I'll rename logging.py to fix for now.~~

**Comment by henryiii** [comment]
Actually, you really should not be running any code from inside the directory. There are other things that will break if you do that. Run from the directory above and it should be fine.

**Comment by davidlange6** [comment]
let me see

**Comment by davidlange6** [comment]
ok - where do I then put a test for my new code? (that I currently have a the end of my module)

**Comment by henryiii** [comment]
If you need to run a file called `processor/x.py`, you can run `python -m processor.x` and it will run the contents with `__name__ == "__main__"`.

**Comment by davidlange6** [comment]
yes - cool. Thanks
