### ISSUE TITLE
Layout question

### ISSUE THREAD

**Issue by henryiii** [Princeton-Penn-Vents/princeton-penn-flowmeter#6]
For 1920x1080, we can't fit the three columns of text at the bottom, and the three plots are crowded. How about moving a few lines below the warning badge, and removing the lower section or changing it to one line of two values? We need to decide exactly what values we will actually show - the limits will probably only be on the "drilled-down screen".

**Comment by davidlange6** [comment]
One option is that limits could be displayed as horizontal lines on the graph itself.


On 8 Apr 2020, at 04:39, Henry Schreiner <notifications@github.com> wrote:

﻿

For 1920x1080, we can't fit the three columns of text at the bottom, and the three plots are crowded. How about moving a few lines below the warning badge, and removing the lower section or changing it to one line of two values? We need to decide exactly what values we will actually show - the limits will probably only be on the "drilled-down screen".
